### ISSUE TITLE
Support building with `scotty-0.22`

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/argo#222]
The upper version bounds in `argo.cabal` currently prevent it from building with `scotty-0.22` (the latest Hackage release as of the time of writing), but we would like to support building with `scotty-0.22` for the sake of being able to build `argo` with more recent GHC versions. Currently, `argo` fails if you try to build with `scotty-0.22`:

```
$ cabal build argo --allow-newer=argo:scotty --constraint="scotty==0.22"
Build profile: -w ghc-9.4.8 -O1
In order, the following will be built (use -v for more details):
 - argo-0.1.0.0 (lib) (first run)
Preprocessing library for argo-0.1.0.0...
Building library for argo-0.1.0.0...
[8 of 9] Compiling Argo.Socket      ( src/Argo/Socket.hs, /Users/rscott/Documents/Hacking/Haskell/argo/dist-newstyle/build/aarch64-osx/ghc-9.4.8/argo-0.1.0.0/build/Argo/Socket.o, /Users/rscott/Documents/Hacking/Haskell/argo/dist-newstyle/build/aarch64-osx/ghc-9.4.8/argo-0.1.0.0/build/Argo/Socket.dyn_o ) [Network.Socket package changed]

src/Argo/Socket.hs:39:15: error:
    • Ambiguous type variable ‘f0’ arising from a use of ‘N.getAddrInfo’
      prevents the constraint ‘(network-3.2.8.0:Network.Socket.Info.GetAddrInfo
                                  f0)’ from being solved.
      Probable fix: use a type annotation to specify what ‘f0’ should be.
      Potentially matching instance:
        instance network-3.2.8.0:Network.Socket.Info.GetAddrInfo []
          -- Defined in ‘network-3.2.8.0:Network.Socket.Info’
        ...plus one instance involving out-of-scope types
        (use -fprint-potential-instances to see them all)
    • In a stmt of a 'do' block:
        infos <- N.getAddrInfo
                   (Just hints) (Just hostName) (Just serviceName)
      In the expression:
        do infos <- N.getAddrInfo
                      (Just hints) (Just hostName) (Just serviceName)
           forConcurrently_ infos $ \ info -> do ...
      In an equation for ‘serveSocket’:
          serveSocket opts hostName serviceName app
            = do infos <- N.getAddrInfo
                            (Just hints) (Just hostName) (Just serviceName)
                 forConcurrently_ infos $ \ info -> ...
   |
39 |   do infos <- N.getAddrInfo (Just hints) (Just hostName) (Just serviceName)
   |               ^^^^^^^^^^^^^

src/Argo/Socket.hs:43:6: error:
    • Ambiguous type variable ‘f0’ arising from a use of ‘forConcurrently_’
      prevents the constraint ‘(Foldable f0)’ from being solved.
      Relevant bindings include
        infos :: f0 N.AddrInfo (bound at src/Argo/Socket.hs:39:6)
      Probable fix: use a type annotation to specify what ‘f0’ should be.
      Potentially matching instances:
        instance Foldable (Either a) -- Defined in ‘Data.Foldable’
        instance Foldable Maybe -- Defined in ‘Data.Foldable’
        ...plus three others
        ...plus 42 instances involving out-of-scope types
        (use -fprint-potential-instances to see them all)
    • In the first argument of ‘($)’, namely ‘forConcurrently_ infos’
      In a stmt of a 'do' block:
        forConcurrently_ infos
          $ \ info
              -> do s <- startListening info
                    forever (acceptClient opts app s)
      In the expression:
        do infos <- N.getAddrInfo
                      (Just hints) (Just hostName) (Just serviceName)
           forConcurrently_ infos $ \ info -> do ...
   |
43 |      forConcurrently_ infos $ \info ->
   |      ^^^^^^^^^^^^^^^^
Error: [Cabal-7125]
Failed to build argo-0.1.0.0.
```

**Comment by RyanGlScott** [comment]
Actually, `scotty-0.22` is a red herring. The _real_ culprit is the fact that the build plan above now includes `network-3.2.*`. Specifically, `network-3.2.3.0` introduced a breaking change in the type of `getAddrInfo`:

```diff
-getAddrInfo ::                  Maybe AddrInfo -> Maybe HostName -> Maybe ServiceName -> IO [AddrInfo]
+getAddrInfo :: GetAddrInfo t => Maybe AddrInfo -> Maybe HostName -> Maybe ServiceName -> IO (t AddrInfo)
```

We will likely need to add an explicit type annotation somewhere in the code in `argo` to ensure that type inference can conclude `t` should be `[]`.
