### ISSUE TITLE
`argo` fails to build with `aeson-2.0.*`

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/argo#187]
`argo` fails to build with `aeson-2.0.0.0` or later:

```
[7 of 9] Compiling Argo             ( src/Argo.hs, /home/rscott/Documents/Hacking/Haskell/argo/dist-newstyle/build/x86_64-linux/ghc-8.10.4/argo-0.1.0.0/build/Argo.o, /home/rscott/Documents/Hacking/Haskell/argo/dist-newstyle/build/x86_64-linux/ghc-8.10.4/argo-0.1.0.0/build/Argo.dyn_o )

src/Argo.hs:1026:29: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap JSON.Value’
                     with ‘HM.HashMap k1 a0’
      Expected type: HM.HashMap k1 a0
        Actual type: JSON.Object
    • In the second argument of ‘HM.member’, namely
        ‘(requestParams req)’
      In the expression: HM.member "state" (requestParams req)
      In the expression:
        if HM.member "state" (requestParams req) then
            throwIO unexpectedStateID
        else
            act
     |
1026 |       if HM.member "state" (requestParams req)
     |                             ^^^^^^^^^^^^^^^^^

src/Argo.hs:1063:27: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap JSON.Value’
                     with ‘HM.HashMap k0 JSON.Value’
      Expected type: HM.HashMap k0 JSON.Value
        Actual type: JSON.Object
    • In the second argument of ‘HM.lookup’, namely
        ‘(requestParams req)’
      In the expression: HM.lookup "state" (requestParams req)
      In the expression:
        case HM.lookup "state" (requestParams req) of
          Just sid
            -> case JSON.fromJSON sid of
                 JSON.Success i -> pure i
                 JSON.Error msg -> noStateID msg
          Nothing -> noStateID "No state field in parameters"
     |
1063 |   case HM.lookup "state" (requestParams req) of
     |                           ^^^^^^^^^^^^^^^^^
```

This is because `aeson` replaces the `HashMap` field of `Object` with a [`KeyMap` type](https://hackage.haskell.org/package/aeson-2.0.1.0/docs/Data-Aeson-KeyMap.html#t:KeyMap). We should adjust the code accordingly.
